### ISSUE TITLE
int32 parameters have type DBF_DOUBLE

### ISSUE THREAD

**Issue by GDYendell** [areaDetector/ADEiger#20]
Various records in the template specify field(DTYP, "asynInt32") and field(PREC, "0"), which makes the native data type DBF_DOUBLE. This causes some issues in higher level applications at DLS as they expect these to be ints and have to work around it being a double.

The records that do this are:
- $(P)$(R)NumTriggers
- $(P)$(R)NumTriggers_RBV
- $(P)$(R)FWNImagesPerFile
- $(P)$(R)FWNImagesPerFile_RBV
- $(P)$(R)StreamDropped_RBV
- $(P)$(R)SequenceId

Does setting PREC = 0 on these records have any desired effects, or could this be removed?

**Comment by brunoseivam** [comment]
> which makes the native data type DBF_DOUBLE

Hmm, I certainly didn't know that could happen! I thought they were DBF_DOUBLE because they are ai/ao records. Maybe they have to be changed to longin/longout?

On a side note, wouldn't it be possible to fetch these values while specifying which type you want to get back? (I'm thinking `caget -d` option)

**Comment by GDYendell** [comment]
> Maybe they have to be changed to longin/longout?
This is probably the better solution. Would this have any undesired effects vs using ai/ao?

**Comment by GDYendell** [comment]
> I thought they were DBF_DOUBLE because they are ai/ao records.

I have just tested this and you are correct. It doesn't matter if PREC is set, it is still DBF_DOUBLE. I guess this makes sense for ao and ai. So, the only solution would be to change to use longin/longout.

**Comment by brunoseivam** [comment]
I wouldn't mind this change. If you open a PR I'd accept it. @MarkRivers , any objections?

**Comment by MarkRivers** [comment]
I agree they should be longout/longin. In general all PVs like this in areaDetector that are inherently integers are longout/longin.
