### ISSUE TITLE
ArrayCounter not updating on abort >1sec exposures

### ISSUE THREAD

**Issue by antoninomiceli** [areaDetector/ADEiger#54]
Byeongdu Lee and Xiaobing Zuo at 12-ID at APS with an Eiger2 S 9M food this issue... 

When we abort a measurement (longer than 1s expsosure), the ioc does not update ArrayCounter properly thereafter. Requiring restart of ioc.

**Comment by MarkRivers** [comment]
This issue is superseded by #56 which has more details.
